volumes:
  pg_volume:

services:
    pg:
        image: postgres:15-alpine3.17
        env_file:
        - .env
        ports:
        - "${POSTGRES_PORT:-5432}:5432"
        volumes:
        - pg_volume:/var/lib/postgresql/data
    backend:
      build:
        context: ./
        dockerfile: backend/Dockerfile
      env_file:
        - .env
      environment:
        HTTP_PORT: ${HTTP_PORT}
        HTTP_HOST: ${HTTP_HOST}
      ports:
        - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
      depends_on:
        - pg

    frontend:
      build:
        context: ./
        dockerfile: frontend/Dockerfile
      env_file:
        - .env
      ports:
        - "${FRONTEND_PORT:-80}:80"
      depends_on:
        - backend